name: poc_localization
description: "PoC Localization"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: 3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

dev_dependencies:
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  generate: true
